Default: &defaults
  database: Stock.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Stock_test.sqlite3
  <<: *defaults

Staging:
  database: Stock_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Stock_production.sqlite3
  poolsize: 100
  <<: *defaults
